version: "3.8"
services:
  carsfullyapplication:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    ports:
      - "4000:4000"
    volumes:
      - .:/user/src/app
